"""Build the model family tree from ``metadata.yaml → parents`` alone.

Writes ``GENEALOGY.md`` (Mermaid graph + table) and ``genealogy.json``.
``--check`` fails if the committed files differ from a fresh build.

Run:  uv run python scripts/build_genealogy.py [--check]
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from feynlag_models import ROOT  # noqa: E402
from feynlag_models import metadata as md  # noqa: E402
from feynlag_models.registry import model_dirs  # noqa: E402


def genealogy():
    metas = {}
    for d in model_dirs():
        metas[d.name] = md.load(d)
    nodes = {}
    for mid, m in metas.items():
        for p in m["parents"]:
            if p not in metas:
                raise SystemExit(f"{mid}: parent {p!r} is not a model")
        nodes[mid] = {"name": m["name"], "parents": list(m["parents"]),
                      "children": [], "maturity_level": m["maturity_level"]}
    for mid, n in nodes.items():
        for p in n["parents"]:
            nodes[p]["children"].append(mid)
    # cycle check by DFS
    state = {}

    def visit(x):
        if state.get(x) == 1:
            raise SystemExit(f"cycle through {x}")
        if state.get(x) == 2:
            return
        state[x] = 1
        for c in nodes[x]["children"]:
            visit(c)
        state[x] = 2

    for x in nodes:
        visit(x)
    return nodes


def render_md(nodes):
    lines = ["# Model genealogy", "",
             "Generated by `scripts/build_genealogy.py` from `metadata.yaml → parents` only. Do not edit.",
             "", "```mermaid", "graph TD"]
    for mid, n in sorted(nodes.items()):
        lines.append(f'    {mid}["{mid}<br/>L{n["maturity_level"]}"]')
    for mid, n in sorted(nodes.items()):
        for p in n["parents"]:
            lines.append(f"    {p} --> {mid}")
    lines += ["```", "", "| id | name | parents | children | maturity |", "|---|---|---|---|---|"]
    for mid, n in sorted(nodes.items()):
        lines.append(f"| `{mid}` | {n['name']} | {', '.join(n['parents']) or '—'} | "
                     f"{', '.join(sorted(n['children'])) or '—'} | L{n['maturity_level']} |")
    return "\n".join(lines) + "\n"


def main(argv):
    nodes = genealogy()
    md_text = render_md(nodes)
    json_text = json.dumps(nodes, indent=2, sort_keys=True) + "\n"
    md_path, json_path = ROOT / "GENEALOGY.md", ROOT / "genealogy.json"
    if "--check" in argv:
        ok = (md_path.exists() and md_path.read_text() == md_text
              and json_path.exists() and json_path.read_text() == json_text)
        print("genealogy up to date" if ok else "genealogy OUT OF DATE — run scripts/build_genealogy.py")
        return 0 if ok else 1
    md_path.write_text(md_text)
    json_path.write_text(json_text)
    print(f"wrote {md_path.name}, {json_path.name} ({len(nodes)} models)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
